# Generated by Django 5.1.7 on 2025-04-14 09:10

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0031_alter_scatadataset_sequences_alter_scatadataset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatadataset',
            name='sequences',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='data/seqs', verbose_name='Sequences'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='tags',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='data/tags', verbose_name='Tag info'),
        ),
    ]
