# Generated by Django 5.2.5 on 2025-11-14 15:22

import django.core.validators
import django.db.models.deletion
import picklefield.fields
import scata2.storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('repseqs', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Number of repseq to report')),
                ('method', models.CharField(choices=[('scata', 'Scata classic'), ('dummy', 'Dummy test')], default='scata', max_length=10, verbose_name='Clustering method')),
                ('status', models.CharField(default='Pending', editable=False, max_length=10, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScataAmplicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('min_length', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Minimum amplicon length is 0'), django.core.validators.MaxValueValidator(10000, 'Max amplicon length is 10kbp')], verbose_name='Minimum length')),
                ('max_length', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0, 'Minimum amplicon length is 0'), django.core.validators.MaxValueValidator(10000, 'Max amplicon length is 10kbp')], verbose_name='Maximum length (max 10kbp)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScataDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('mean_qual', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10, 'Min is 10'), django.core.validators.MaxValueValidator(100, 'Max is 100')], verbose_name='Minimum mean read quality')),
                ('min_qual', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Min is 1'), django.core.validators.MaxValueValidator(100, 'Max is 100')], verbose_name='Minimum quality of any base')),
                ('kmer_size', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(5, 'Min is 5'), django.core.validators.MaxValueValidator(15, 'Max is 15')], verbose_name='Overlap join: kmer size')),
                ('kmer_hsp_count', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(3, 'Min is 3'), django.core.validators.MaxValueValidator(10, 'Max is 10')], verbose_name='Overlap join: HSP adjacent kmers')),
                ('kmer_shared', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5, 'Min is 5'), django.core.validators.MaxValueValidator(20, 'Max is 20')], verbose_name='Overlap join: number of shared kmers')),
                ('filter_method', models.CharField(choices=[('fsq', 'Full sequence, quality screen'), ('fs', 'Full sequence, NO quality filtering'), ('ampq', 'Amplicon quality'), ('amp', 'Only amplicon extraction')], default='ampq', max_length=6, verbose_name='Filtering type')),
                ('file_types', models.CharField(choices=[('fastq', 'First file FASTQ'), ('fastp', 'Paired End FASTQ (two files with mates)'), ('fasta', 'First file FASTA'), ('fastaq', 'First file FASTA, second file quality data')], default='fastq', max_length=6, verbose_name='File types')),
                ('is_valid', models.BooleanField(default=False, editable=False)),
                ('validated', models.BooleanField(default=False)),
                ('has_stats', models.BooleanField(default=False, editable=False)),
                ('progress', models.CharField(default='', max_length=100)),
                ('seq_count', models.IntegerField(default=0, editable=False)),
                ('seq_total', models.IntegerField(default=0, editable=False)),
                ('seq_rev', models.IntegerField(default=0, editable=False)),
                ('tag_count', models.IntegerField(default=0, editable=False)),
                ('pc1_exp', models.FloatField(default=0)),
                ('pc2_exp', models.FloatField(default=0)),
                ('pc3_exp', models.FloatField(default=0)),
                ('process_time', models.FloatField(default=0.0, editable=False)),
                ('tags', models.FileField(blank=True, editable=False, null=True, storage=scata2.storages.get_work_storage, upload_to='data/tags', verbose_name='Tag info')),
                ('sequences', models.FileField(blank=True, editable=False, null=True, storage=scata2.storages.get_work_storage, upload_to='data/seqs', verbose_name='Sequences')),
                ('amplicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon for filtering')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScataDummyMethod',
            fields=[
                ('scatamethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scata2.scatamethod')),
                ('dummy', models.CharField(choices=[('foo', 'Foo'), ('bar', 'Bar')], default='foo', verbose_name='Dummy setting')),
                ('num_seqs', models.IntegerField(default=0, editable=False, verbose_name='Number of sequences')),
                ('num_refs', models.IntegerField(default=0, editable=False, verbose_name='Number of reference sequences')),
                ('mean_len', models.IntegerField(default=0, editable=False, verbose_name='Mean sequence length')),
                ('num_clusters', models.IntegerField(default=0, editable=False, verbose_name='Number of clusters (unique sequences)')),
            ],
            bases=('scata2.scatamethod',),
        ),
        migrations.CreateModel(
            name='ScataScataMethod',
            fields=[
                ('scatamethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scata2.scatamethod')),
                ('distance', models.FloatField(default=0.015, validators=[django.core.validators.MinValueValidator(0.001, 'Min 0.001'), django.core.validators.MaxValueValidator(0.1, 'Max 0.10')], verbose_name='Clustering distance 0.001 < x < 0.10')),
                ('min_alignment', models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.5, 'Min 0.5'), django.core.validators.MaxValueValidator(1.0, 'Max 1')], verbose_name='Minimum alignment 0.5 < x < 1.0. Set to 1.0 to force global clustering (if all references are extracted amplicons)')),
                ('mismatch_pen', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Mismatch penalty 0 < x < 100')),
                ('open_pen', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Gap open penalty 0 < x < 100')),
                ('extend_pen', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Gap extension penalty 0 < x < 100')),
                ('endgap_pen', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='End gap weight 0 < x < 100')),
                ('max_homopolymer', models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(10, 'Max 10')], verbose_name='Collapse homopolymers longer than this. 0 to disable')),
                ('downsample', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100000.0, 'Max 1e5')], verbose_name='Downsample samples with more than this number of reads to this number. 0 to disable.')),
                ('lowfreq', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Remove global low frequency genotypes occurring less than this number of times.')),
            ],
            bases=('scata2.scatamethod',),
        ),
        migrations.CreateModel(
            name='ScataErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatadataset')),
            ],
        ),
        migrations.CreateModel(
            name='ScataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('file', models.FileField(storage=scata2.storages.get_file_storage, upload_to='', verbose_name='File')),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('sha256', models.CharField(default='', max_length=100, verbose_name='Sha256 Sum')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='file1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_file1', to='scata2.scatafile', verbose_name='File 1'),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='file2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_file2', to='scata2.scatafile', verbose_name='File 2'),
        ),
        migrations.AddField(
            model_name='scatamethod',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob'),
        ),
        migrations.AddField(
            model_name='scatajob',
            name='amplicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon to use for clusteringleave unset to use full imported amplicon'),
        ),
        migrations.AddField(
            model_name='scatajob',
            name='datasets',
            field=models.ManyToManyField(to='scata2.scatadataset', verbose_name='Datasets'),
        ),
        migrations.AddField(
            model_name='scatajob',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScataOTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob')),
            ],
        ),
        migrations.CreateModel(
            name='ScataPrimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('sequence', models.CharField(max_length=100, verbose_name='Primer sequence (IUPAC ambiguity codes are accepted)')),
                ('mismatches', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Max mismatches')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scataamplicon',
            name='five_prime_primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='five_prime_primer', to='scata2.scataprimer', verbose_name="5' primer"),
        ),
        migrations.AddField(
            model_name='scataamplicon',
            name='three_prime_primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_prime_primer', to='scata2.scataprimer', verbose_name="3' primer"),
        ),
        migrations.CreateModel(
            name='ScataReferenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_valid', models.BooleanField(default=False, editable=False)),
                ('validated', models.BooleanField(default=False, editable=False)),
                ('sequences', models.FileField(blank=True, editable=False, null=True, storage=scata2.storages.get_work_storage, upload_to='data/seqs', verbose_name='Sequences')),
                ('progress', models.CharField(default='', max_length=100)),
                ('seq_count', models.IntegerField(default=0, editable=False)),
                ('seq_total', models.IntegerField(default=0, editable=False)),
                ('process_time', models.FloatField(default=0.0, editable=False)),
                ('amplicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Filter database to contain region defined by this amplicon. Leave empty to disable.')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refseq_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scata2.scatafile', verbose_name='File with references')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scatajob',
            name='refsets',
            field=models.ManyToManyField(blank=True, to='scata2.scatareferenceset', verbose_name='References'),
        ),
        migrations.CreateModel(
            name='ScataRefsetErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('refset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatareferenceset')),
            ],
        ),
        migrations.CreateModel(
            name='ScataRepSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(default='', max_length=2000)),
                ('length', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('otu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scataotu')),
            ],
        ),
        migrations.CreateModel(
            name='ScataTagSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('errors', models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_valid', models.BooleanField(default=False, editable=False, verbose_name='Valid')),
                ('validated', models.BooleanField(default=False, editable=False, verbose_name='Validated')),
                ('num_tags', models.IntegerField(default=0, editable=False, verbose_name='Number if tags')),
                ('tags', picklefield.fields.PickledObjectField(compress=True, editable=False, null=True, verbose_name='Data (dict)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagset_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scata2.scatafile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scataamplicon',
            name='five_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='five_prime_tagset', to='scata2.scatatagset', verbose_name="5' tagset (not used when clustering)"),
        ),
        migrations.AddField(
            model_name='scataamplicon',
            name='three_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='three_prime_tagset', to='scata2.scatatagset', verbose_name="3' tagset (not used when clustering)"),
        ),
        migrations.CreateModel(
            name='ScataTagStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('reversed', models.IntegerField()),
                ('mean_len', models.FloatField()),
                ('min_len', models.IntegerField()),
                ('max_len', models.IntegerField()),
                ('min_gc', models.FloatField()),
                ('mean_gc', models.FloatField()),
                ('max_gc', models.FloatField()),
                ('in_pca', models.BooleanField(default=False)),
                ('pc1', models.FloatField(default=0)),
                ('pc2', models.FloatField(default=0)),
                ('pc3', models.FloatField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatadataset')),
            ],
        ),
    ]
