# Generated by Django 5.1.7 on 2025-03-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataPrimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='Create date')),
                ('short_name', models.CharField(max_length=20, verbose_name='Short name')),
                ('sequence', models.CharField(max_length=100, verbose_name='Primer sequence')),
                ('missmatches', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Max missmatches')),
                ('description', models.TextField(max_length='1000')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
