# Generated by Django 5.2.5 on 2025-11-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataScataMethodChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('num_sequences', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='scata/methods/scata/chunk/')),
                ('job_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatascatamethod')),
            ],
        ),
    ]
