# Generated by Django 5.2.5 on 2025-11-17 14:37

import django.db.models.deletion
import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0002_scatascatamethodchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataSequenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('num_sequences', models.IntegerField(default=0)),
                ('file', models.FileField(storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/chunk/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob')),
            ],
        ),
        migrations.DeleteModel(
            name='ScataScataMethodChunk',
        ),
    ]
