# Generated by Django 5.1.7 on 2025-03-11 14:57

import django.db.models.deletion
import json.decoder
import json.encoder
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0002_scataprimer_public_alter_scataprimer_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='scataprimer',
            old_name='missmatches',
            new_name='mismatches',
        ),
        migrations.AlterField(
            model_name='scataprimer',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.CreateModel(
            name='ScataTagSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('name', models.CharField(max_length=50, verbose_name='Tagset Name')),
                ('is_valid', models.BooleanField(default=False, editable=False, verbose_name='Valid')),
                ('validated', models.BooleanField(default=False, editable=False, verbose_name='Validated')),
                ('tags', models.JSONField(decoder=json.decoder.JSONDecoder, editable=False, encoder=json.encoder.JSONEncoder, verbose_name='Data (dict)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
