# Generated by Django 5.1.7 on 2025-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0003_rename_missmatches_scataprimer_mismatches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatatagset',
            name='num_tags',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number if tags'),
        ),
    ]
