# Generated by Django 5.2.5 on 2025-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0003_scatasequencechunk_delete_scatascatamethodchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatasequencechunk',
            name='num_uniques',
            field=models.IntegerField(default=0),
        ),
    ]
