# Generated by Django 5.2.5 on 2026-01-13 15:04

import django.db.models.deletion
import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0004_scatasequencechunk_num_uniques'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataScataSubCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/subcluster/')),
                ('level', models.PositiveIntegerField(default=0)),
                ('scata_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatascatamethod')),
            ],
        ),
    ]
