# Generated by Django 5.1.7 on 2025-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0004_scatatagset_num_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatatagset',
            name='tagset_file',
            field=models.FileField(null=True, upload_to='tagsets/', verbose_name='Tagset File'),
        ),
    ]
