# Generated by Django 5.1.7 on 2025-03-12 23:05

import json.decoder
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0005_scatatagset_tagset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatatagset',
            name='tags',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, editable=False, encoder=json.encoder.JSONEncoder, null=True, verbose_name='Data (dict)'),
        ),
    ]
