# Generated by Django 5.2.5 on 2026-01-13 15:16

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0005_scatascatasubcluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatascatasubcluster',
            name='file',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/subcluster/'),
        ),
    ]
