# Generated by Django 5.1.7 on 2025-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0006_alter_scatatagset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scataprimer',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='scatatagset',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
