# Generated by Django 5.2.5 on 2026-01-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0006_alter_scatascatasubcluster_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatascatasubcluster',
            name='scata_method',
        ),
        migrations.AddField(
            model_name='scatascatasubcluster',
            name='job',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob'),
            preserve_default=False,
        ),
    ]
