# Generated by Django 5.2.5 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0007_remove_scatascatasubcluster_scata_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scataerrortype',
            name='error',
            field=models.CharField(max_length=100),
        ),
    ]
