# Generated by Django 5.1.7 on 2025-03-14 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0007_scataprimer_trashed_scatatagset_trashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('name', models.CharField(max_length=50, verbose_name='File Name')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Description')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('sha256', models.CharField(default='', max_length=100, verbose_name='Sha256 Sum')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
