# Generated by Django 5.2.5 on 2026-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0008_alter_scataerrortype_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatajob',
            name='status',
            field=models.CharField(default='Pending', editable=False, max_length=250, verbose_name='Status'),
        ),
    ]
