# Generated by Django 5.1.7 on 2025-03-14 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0008_scatafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatatagset',
            name='tagset_file',
        ),
        migrations.AddField(
            model_name='scatatagset',
            name='Tagset File',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scata2.scatafile'),
        ),
    ]
