# Generated by Django 5.2.5 on 2026-01-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0009_alter_scatajob_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scataamplicon',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scatadataset',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scatafile',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scatajob',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scataprimer',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scatareferenceset',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='scatatagset',
            options={'ordering': ['-create_date']},
        ),
    ]
