# Generated by Django 5.1.7 on 2025-03-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0009_remove_scatatagset_tagset_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatatagset',
            name='Tagset File',
        ),
        migrations.AddField(
            model_name='scatatagset',
            name='tagset_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scata2.scatafile'),
        ),
    ]
