# Generated by Django 5.2.5 on 2026-01-21 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0010_alter_scataamplicon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(editable=False, verbose_name='Cluster size')),
                ('num_reversed', models.IntegerField(editable=False, verbose_name='Number of reversed sequences')),
                ('num_genotypes', models.IntegerField(editable=False, verbose_name='Number of genotypes')),
                ('num_singletons', models.IntegerField(editable=False, verbose_name='Number of singleton sequences')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob')),
            ],
        ),
        migrations.CreateModel(
            name='ScataClusterGenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(editable=False, verbose_name='Sequence')),
                ('frequency', models.FloatField(editable=False, verbose_name='Frequency')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatacluster')),
            ],
        ),
        migrations.CreateModel(
            name='ScataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(editable=False, verbose_name='Total reads')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob')),
            ],
        ),
        migrations.CreateModel(
            name='ScataTagCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(editable=False, verbose_name='Cluster size')),
                ('sequences', models.FileField(blank=True, null=True, upload_to='', verbose_name='Cluster sequences')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatacluster')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatatag')),
            ],
        ),
    ]
