# Generated by Django 5.1.7 on 2025-03-17 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0010_remove_scatatagset_tagset_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataAmplicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('name', models.CharField(max_length=50, verbose_name='Amplicon name')),
                ('min_length', models.IntegerField(default=0, verbose_name='Minimum length')),
                ('max_length', models.IntegerField(default=0, verbose_name='Maximum length (0 -> no limit)')),
                ('five_prime_primer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_prime_primer', to='scata2.scataprimer', verbose_name="5' primer")),
                ('five_prime_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_prime_tagset', to='scata2.scatatagset', verbose_name="5' tagset")),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('three_prime_primer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_prime_primer', to='scata2.scataprimer', verbose_name="3' primer")),
                ('three_prime_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_prime_tagset', to='scata2.scatatagset', verbose_name="3' tagset")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
