# Generated by Django 5.1.7 on 2025-03-18 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0011_scataamplicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='scataamplicon',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='five_prime_primer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_prime_primer', to='scata2.scataprimer', verbose_name="5' primer"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='five_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_prime_tagset', to='scata2.scatatagset', verbose_name="5' tagset"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='max_length',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0, 'Minimum amplicon length is 0'), django.core.validators.MaxValueValidator(10000, 'Max amplicon length is 10kbp')], verbose_name='Maximum length (max 10kbp)'),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='min_length',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Minimum amplicon length is 0'), django.core.validators.MaxValueValidator(10000, 'Max amplicon length is 10kbp')], verbose_name='Minimum length'),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='three_prime_primer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_prime_primer', to='scata2.scataprimer', verbose_name="3' primer"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='three_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_prime_tagset', to='scata2.scatatagset', verbose_name="3' tagset"),
        ),
    ]
