# Generated by Django 5.2.5 on 2026-01-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0011_scatacluster_scataclustergenotype_scatatag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatascatamethod',
            name='pre_clusters',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Pre clusters'),
        ),
    ]
