# Generated by Django 5.1.7 on 2025-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0012_scataamplicon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scataprimer',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Short name'),
        ),
    ]
