# Generated by Django 5.2.5 on 2026-01-21 18:48

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0012_scatascatamethod_pre_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatascatamethod',
            name='pre_clusters',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/subcluster/', verbose_name='Pre clusters'),
        ),
    ]
