# Generated by Django 5.1.7 on 2025-03-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0013_alter_scataprimer_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scataprimer',
            old_name='short_name',
            new_name='name',
        ),
    ]
