# Generated by Django 5.2.5 on 2026-01-22 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0014_alter_scatascatamethod_pre_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatascatamethod',
            name='downsample',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100000.0, 'Max 1e5')], verbose_name='Downsample samples with more than this number of reads to this number. 0 to disable.'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='endgap_pen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='End gap scaling 0 < x < 100.'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='extend_pen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Gap extension penalty 0 < x < 100'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='lowfreq',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Remove global low frequency genotypes occurring less than this number of times.'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='max_homopolymer',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(10, 'Max 10')], verbose_name='Collapse homopolymers longer than this. 0 to disable'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='min_alignment',
            field=models.IntegerField(default=0.9, validators=[django.core.validators.MinValueValidator(0.5, 'Min 0.5'), django.core.validators.MaxValueValidator(1.0, 'Max 1')], verbose_name='Minimum alignment 0.5 < x < 1.0. Set to 1.0 to force global clustering (if all references are extracted amplicons)'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='mismatch_pen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Mismatch penalty 0 < x < 100'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='open_pen',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Gap open penalty 0 < x < 100'),
        ),
    ]
