# Generated by Django 5.1.7 on 2025-03-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0015_scatatagset_description_alter_scataamplicon_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataReferenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_valid', models.BooleanField(default=False, editable=False, verbose_name='Valid')),
                ('validated', models.BooleanField(default=False, editable=False, verbose_name='Validated')),
                ('num_seqs', models.IntegerField(default=0, editable=False, verbose_name='Number if tags')),
                ('refseq', models.FileField(editable=False, upload_to='')),
                ('seq_count', models.IntegerField(default=0, editable=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refseq_file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scata2.scatafile', verbose_name='File with references')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
