# Generated by Django 5.2.5 on 2026-01-22 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0015_alter_scatascatamethod_downsample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatascatamethod',
            name='num_genotypes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of genotypes'),
        ),
        migrations.AddField(
            model_name='scatascatamethod',
            name='total_size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total size number of reads'),
        ),
        migrations.AlterField(
            model_name='scatascatamethod',
            name='min_alignment',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.5, 'Min 0.5'), django.core.validators.MaxValueValidator(1.0, 'Max 1')], verbose_name='Minimum alignment 0.5 < x < 1.0. Set to 1.0 to force global clustering (if all references are extracted amplicons)'),
        ),
    ]
