# Generated by Django 5.1.7 on 2025-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0016_scatareferenceset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatareferenceset',
            name='refseq',
            field=models.FileField(editable=False, null=True, upload_to=''),
        ),
    ]
