# Generated by Django 5.2.5 on 2026-01-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0016_scatascatamethod_num_genotypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatajob',
            name='completed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Process completed'),
        ),
    ]
