# Generated by Django 5.1.7 on 2025-03-21 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0017_alter_scatareferenceset_refseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatareferenceset',
            name='amplicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Filter database to contain region defined by this amplicon. Leave empty to disable.'),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='five_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five_prime_tagset', to='scata2.scatatagset', verbose_name="5' tagset (not used when clustering)"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='three_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_prime_tagset', to='scata2.scatatagset', verbose_name="3' tagset (not used when clustering)"),
        ),
        migrations.AlterField(
            model_name='scatareferenceset',
            name='is_valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='scatareferenceset',
            name='num_seqs',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='scatareferenceset',
            name='refseq_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scata2.scatafile', verbose_name='File with references'),
        ),
        migrations.AlterField(
            model_name='scatareferenceset',
            name='validated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
