# Generated by Django 5.2.5 on 2026-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0017_scatajob_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatajob',
            name='completed_date',
            field=models.DateTimeField(null=True, verbose_name='Completed date'),
        ),
    ]
