# Generated by Django 5.1.7 on 2025-03-22 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0018_scatareferenceset_amplicon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('mean_qual', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10, 'Min is 10'), django.core.validators.MaxValueValidator(100, 'Max is 100')], verbose_name='Minimum mean read quality')),
                ('min_qual', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1, 'Min is 1'), django.core.validators.MaxValueValidator(100, 'Max is 100')], verbose_name='Minimum quality of any base')),
                ('kmer_size', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(10, 'Min is 5'), django.core.validators.MaxValueValidator(100, 'Max is 15')], verbose_name='Overlap join: kmer size')),
                ('kmer_hsp_count', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(10, 'Min is 3'), django.core.validators.MaxValueValidator(100, 'Max is 10')], verbose_name='Overlap join: HSP adjacent kmers')),
                ('kmer_shared', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10, 'Min is 5'), django.core.validators.MaxValueValidator(100, 'Max is 20')], verbose_name='Overlap join: number of shared kmers')),
                ('filter_method', models.CharField(choices=[('fsq', 'Full sequence, quality screen'), ('fs', 'Full sequence, NO quality filtering'), ('hqr', 'Extract High Quality Region'), ('ampq', 'Amplicon quality')], max_length=5, verbose_name='Filtering type')),
                ('amplicon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon for filtering')),
                ('file1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_file1', to='scata2.scatafile', verbose_name='File 1')),
                ('file2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_file2', to='scata2.scatafile', verbose_name='File 2')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
