# Generated by Django 5.2.5 on 2026-01-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0018_scatajob_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='short_name',
            field=models.CharField(default='', verbose_name='Short name (used as label in output)'),
        ),
    ]
