# Generated by Django 5.2.5 on 2026-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0019_scatadataset_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatatag',
            name='name',
            field=models.CharField(default='', editable=False, max_length=200, verbose_name='Name'),
        ),
    ]
