# Generated by Django 5.1.7 on 2025-03-22 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0019_scatadataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatareferenceset',
            name='num_seqs',
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='is_valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='seq_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='validated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='kmer_hsp_count',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(3, 'Min is 3'), django.core.validators.MaxValueValidator(10, 'Max is 10')], verbose_name='Overlap join: HSP adjacent kmers'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='kmer_shared',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5, 'Min is 5'), django.core.validators.MaxValueValidator(20, 'Max is 20')], verbose_name='Overlap join: number of shared kmers'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='kmer_size',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(5, 'Min is 5'), django.core.validators.MaxValueValidator(15, 'Max is 15')], verbose_name='Overlap join: kmer size'),
        ),
    ]
