# Generated by Django 5.2.5 on 2026-01-28 09:31

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0020_scatatag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatascatamethod',
            name='tags',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/tags/', verbose_name='Tags'),
        ),
    ]
