# Generated by Django 5.2.5 on 2026-01-28 14:17

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0021_scatascatamethod_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatascatamethod',
            name='id2name',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/id2name/', verbose_name='Tags'),
        ),
    ]
