# Generated by Django 5.1.7 on 2025-03-26 20:36

import picklefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0021_scatajob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatatagset',
            name='tags',
            field=picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name='Data (dict)'),
        ),
    ]
