# Generated by Django 5.1.7 on 2025-03-27 08:50

import picklefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0022_alter_scatatagset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatatagset',
            name='tags',
            field=picklefield.fields.PickledObjectField(compress=True, editable=False, null=True, verbose_name='Data (dict)'),
        ),
    ]
