# Generated by Django 5.2.5 on 2026-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0022_scatascatamethod_id2name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatacluster',
            name='num_genotypes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of genotypes'),
        ),
        migrations.AlterField(
            model_name='scatacluster',
            name='num_reversed',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of reversed sequences'),
        ),
        migrations.AlterField(
            model_name='scatacluster',
            name='num_singletons',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of singleton sequences'),
        ),
        migrations.AlterField(
            model_name='scatacluster',
            name='size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster size'),
        ),
    ]
