# Generated by Django 5.1.7 on 2025-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0023_alter_scatatagset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scataamplicon',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
        migrations.AddField(
            model_name='scatafile',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
        migrations.AddField(
            model_name='scatajob',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
        migrations.AddField(
            model_name='scataprimer',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
        migrations.AddField(
            model_name='scatareferenceset',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
        migrations.AddField(
            model_name='scatatagset',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=4000, verbose_name='Error description'),
        ),
    ]
