# Generated by Django 5.2.5 on 2026-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0023_alter_scatacluster_num_genotypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatascatamethod',
            name='num_clusters',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of clusters'),
        ),
        migrations.AddField(
            model_name='scatascatamethod',
            name='num_singletons',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of global singleton sequences'),
        ),
    ]
