# Generated by Django 5.1.7 on 2025-03-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0024_scataamplicon_errors_scatadataset_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scataamplicon',
            name='five_prime_primer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='five_prime_primer', to='scata2.scataprimer', verbose_name="5' primer"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='five_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='five_prime_tagset', to='scata2.scatatagset', verbose_name="5' tagset (not used when clustering)"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='three_prime_primer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='three_prime_primer', to='scata2.scataprimer', verbose_name="3' primer"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='three_prime_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='three_prime_tagset', to='scata2.scatatagset', verbose_name="3' tagset (not used when clustering)"),
        ),
    ]
