# Generated by Django 5.2.5 on 2026-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0024_scatascatamethod_num_clusters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatacluster',
            name='cluster_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
