# Generated by Django 5.2.5 on 2026-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0025_scatacluster_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatatag',
            name='num_clusters',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of clusters'),
        ),
        migrations.AlterField(
            model_name='scatatag',
            name='size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total reads'),
        ),
    ]
