# Generated by Django 5.1.7 on 2025-04-04 10:45

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0025_alter_scataamplicon_five_prime_primer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='file_types',
            field=models.CharField(choices=[('fastq', 'First file FASTQ (should be gzipped)'), ('fasta', 'First file FASTA (should be gzipped)'), ('fastaq', 'First file FASTA, second QUAL (both should be gzipped)')], default='fastq', max_length=6, verbose_name='File types'),
        ),
        migrations.AlterField(
            model_name='scatafile',
            name='file',
            field=models.FileField(storage=scata2.storages.get_file_storage, upload_to='', verbose_name='File'),
        ),
    ]
