# Generated by Django 5.2.5 on 2026-02-03 13:14

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0026_scatatag_num_clusters_alter_scatatag_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scatacluster',
            old_name='cluster_id',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='scatatagcluster',
            name='sequences',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='scata/methods/scata/tag/', verbose_name='Cluster sequences'),
        ),
        migrations.AlterField(
            model_name='scatatagcluster',
            name='size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cluster size'),
        ),
    ]
