# Generated by Django 5.1.7 on 2025-04-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0026_scatadataset_file_types_alter_scatafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatadataset',
            name='amplicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon for filtering'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='file_types',
            field=models.CharField(choices=[('fastq', 'First file FASTQ'), ('fastp', 'Paired End FASTQ (two files with mates)'), ('fasta', 'First file FASTA'), ('fastaq', 'First file FASTA, second file quality data')], default='fastq', max_length=6, verbose_name='File types'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='filter_method',
            field=models.CharField(choices=[('fsq', 'Full sequence, quality screen'), ('fs', 'Full sequence, NO quality filtering'), ('hqr', 'Extract High Quality Region'), ('ampq', 'Amplicon quality'), ('none', 'No no quality filtering')], default='ampq', max_length=6, verbose_name='Filtering type'),
        ),
        migrations.AlterField(
            model_name='scataprimer',
            name='sequence',
            field=models.CharField(max_length=100, verbose_name='Primer sequence (IUPAC ambiguity codes are accepted)'),
        ),
    ]
