# Generated by Django 5.1.7 on 2025-04-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0027_alter_scatadataset_amplicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='progress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='five_prime_primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='five_prime_primer', to='scata2.scataprimer', verbose_name="5' primer"),
        ),
        migrations.AlterField(
            model_name='scataamplicon',
            name='three_prime_primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_prime_primer', to='scata2.scataprimer', verbose_name="3' primer"),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='filter_method',
            field=models.CharField(choices=[('fsq', 'Full sequence, quality screen'), ('fs', 'Full sequence, NO quality filtering'), ('ampq', 'Amplicon quality'), ('amp', 'Only amplicon extraction')], default='ampq', max_length=6, verbose_name='Filtering type'),
        ),
    ]
