# Generated by Django 5.1.7 on 2025-04-11 21:34

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0028_scatadataset_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='sequences',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='', verbose_name='Sequences'),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='tags',
            field=models.FileField(blank=True, null=True, storage=scata2.storages.get_work_storage, upload_to='', verbose_name='Tag info'),
        ),
    ]
