# Generated by Django 5.1.7 on 2025-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0030_alter_scatadataset_sequences_alter_scatadataset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scatadataset',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
