# Generated by Django 5.1.7 on 2025-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0031_alter_scatadataset_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='process_time',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='seq_total',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
