# Generated by Django 5.1.7 on 2025-04-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0032_scatadataset_process_time_scatadataset_seq_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatadataset')),
            ],
        ),
    ]
