# Generated by Django 5.1.7 on 2025-04-15 13:09

import scata2.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0033_scataerrortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatareferenceset',
            name='process_time',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='scatareferenceset',
            name='progress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scatareferenceset',
            name='seq_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scatareferenceset',
            name='sequences',
            field=models.FileField(blank=True, editable=False, null=True, storage=scata2.storages.get_work_storage, upload_to='data/seqs', verbose_name='Sequences'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='sequences',
            field=models.FileField(blank=True, editable=False, null=True, storage=scata2.storages.get_work_storage, upload_to='data/seqs', verbose_name='Sequences'),
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='tags',
            field=models.FileField(blank=True, editable=False, null=True, storage=scata2.storages.get_work_storage, upload_to='data/tags', verbose_name='Tag info'),
        ),
    ]
