# Generated by Django 5.1.7 on 2025-04-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0034_scatareferenceset_process_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScataRefsetErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatareferenceset')),
            ],
        ),
    ]
