# Generated by Django 5.1.7 on 2025-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0037_scatajob_datasets_scatajob_refsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scataamplicon',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scataprimer',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
