# Generated by Django 5.1.7 on 2025-05-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0038_alter_scataamplicon_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatareferenceset',
            name='refseq',
        ),
    ]
