# Generated by Django 5.1.7 on 2025-05-10 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0039_remove_scatareferenceset_refseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='has_stats',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='ScataTagStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('mean_len', models.IntegerField()),
                ('min_len', models.IntegerField()),
                ('max_len', models.IntegerField()),
                ('gc', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatadataset')),
            ],
        ),
    ]
