# Generated by Django 5.1.7 on 2025-05-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0040_scatadataset_has_stats_scatatagstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='seq_rev',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
