# Generated by Django 5.1.7 on 2025-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0041_scatadataset_seq_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='tag_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
