# Generated by Django 5.1.7 on 2025-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0042_scatadataset_tag_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scatatagstat',
            old_name='gc',
            new_name='max_gc',
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='mean_gc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='min_gc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='reversed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scatatagstat',
            name='mean_len',
            field=models.FloatField(),
        ),
    ]
