# Generated by Django 5.1.7 on 2025-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0043_rename_gc_scatatagstat_max_gc_scatatagstat_mean_gc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatadataset',
            name='pc1_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='pc2_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scatadataset',
            name='pc3_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='in_pca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='pc1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='pc2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scatatagstat',
            name='pc3',
            field=models.FloatField(default=0),
        ),
    ]
