# Generated by Django 5.2.5 on 2025-08-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0044_scatadataset_pc1_exp_scatadataset_pc2_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatajob',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='downsample',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='endgap_pen',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='extend_pen',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='lowfreq',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='max_homopolymer',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='min_alignment',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='mismatch_pen',
        ),
        migrations.RemoveField(
            model_name='scatajob',
            name='open_pen',
        ),
    ]
