# Generated by Django 5.2.5 on 2025-10-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0046_scatamethod_scatajob_method_dummymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatamethod',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob'),
            preserve_default=False,
        ),
    ]
