# Generated by Django 5.2.5 on 2025-10-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0047_scatamethod_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='scatamethod',
            name='amplicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon to use for clustering'),
        ),
        migrations.AlterField(
            model_name='scatajob',
            name='method',
            field=models.CharField(choices=[('scata', 'Scata classic'), ('dummy', 'Dummy test')], default='scata', max_length=10, verbose_name='Clustering method'),
        ),
        migrations.AlterField(
            model_name='scatajob',
            name='status',
            field=models.CharField(default='Pending', editable=False, max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scatamethod',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scata2.scatajob', unique=True),
        ),
    ]
