# Generated by Django 5.2.5 on 2025-10-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0048_scatamethod_amplicon_alter_scatajob_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scatamethod',
            name='amplicon',
        ),
        migrations.AddField(
            model_name='scatajob',
            name='amplicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon to use for clustering'),
        ),
    ]
