# Generated by Django 5.2.5 on 2025-11-04 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0049_remove_scatamethod_amplicon_scatajob_amplicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummymethod',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dummymethod',
            name='job',
        ),
        migrations.RemoveField(
            model_name='scatamethod',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scatamethod',
            name='job',
        ),
        migrations.AlterField(
            model_name='scatadataset',
            name='min_qual',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Min is 1'), django.core.validators.MaxValueValidator(100, 'Max is 100')], verbose_name='Minimum quality of any base'),
        ),
        migrations.AlterField(
            model_name='scatajob',
            name='amplicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scata2.scataamplicon', verbose_name='Amplicon to use for clusteringleave unset to use full imported amplicon'),
        ),
        migrations.AlterField(
            model_name='scatamethod',
            name='lowfreq',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(100, 'Max 100')], verbose_name='Remove global low frequency genotypes occurring less than this number of times.'),
        ),
        migrations.AlterField(
            model_name='scatamethod',
            name='max_homopolymer',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0, 'Min 0'), django.core.validators.MaxValueValidator(10, 'Max 10')], verbose_name='Collapse homopolymers longer than this. 0 to disable'),
        ),
        migrations.AlterField(
            model_name='scataprimer',
            name='mismatches',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Max mismatches'),
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_method', to='scata2.scatajob')),
            ],
        ),
        migrations.AddField(
            model_name='dummymethod',
            name='method_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scata2.method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scatamethod',
            name='method_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scata2.method'),
            preserve_default=False,
        ),
    ]
