# Generated by Django 5.2.5 on 2025-11-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0050_remove_dummymethod_id_remove_dummymethod_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymethod',
            name='mean_len',
            field=models.IntegerField(default=0, editable=False, verbose_name='Mean sequence length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummymethod',
            name='num_refs',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of reference sequences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummymethod',
            name='num_seqs',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of sequences'),
            preserve_default=False,
        ),
    ]
