# Generated by Django 5.2.5 on 2025-11-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0051_dummymethod_mean_len_dummymethod_num_refs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummymethod',
            name='mean_len',
            field=models.IntegerField(default=0, editable=False, verbose_name='Mean sequence length'),
        ),
        migrations.AlterField(
            model_name='dummymethod',
            name='num_refs',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of reference sequences'),
        ),
        migrations.AlterField(
            model_name='dummymethod',
            name='num_seqs',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of sequences'),
        ),
    ]
