# Generated by Django 5.2.5 on 2025-11-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0052_alter_dummymethod_mean_len_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymethod',
            name='num_clusters',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of clusters (unique sequences)'),
            preserve_default=False,
        ),
    ]
