# Generated by Django 5.2.5 on 2025-11-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scata2', '0053_dummymethod_num_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummymethod',
            name='num_clusters',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number of clusters (unique sequences)'),
        ),
    ]
